"""init

Revision ID: 7100486962bc
Revises: 
Create Date: 2026-04-07 17:09:29.118665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7100486962bc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment_types',
    sa.Column('type_name', sa.String(length=200), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type_name')
    )
    op.create_table('equipment',
    sa.Column('equipment_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('equipment_type_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['equipment_type_id'], ['equipment_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('equipment_code')
    )
    op.create_table('downtimes',
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('reason_category', sa.String(length=100), nullable=True),
    sa.Column('reason_details', sa.Text(), nullable=True),
    sa.Column('production_loss_units', sa.Float(), nullable=True),
    sa.Column('cost_impact_rub', sa.Float(), nullable=True),
    sa.Column('reported_by', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inspections',
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('inspector_name', sa.String(length=100), nullable=False),
    sa.Column('check_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('ok', 'warning', 'critical', name='inspection_status'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('photos_urls', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hypotheses',
    sa.Column('downtime_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('problem_description', sa.Text(), nullable=False),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('suggested_action', sa.Text(), nullable=False),
    sa.Column('expected_downtime_reduction_hours', sa.Float(), nullable=True),
    sa.Column('expected_cost_savings_rub', sa.Float(), nullable=True),
    sa.Column('implementation_cost_rub', sa.Float(), nullable=True),
    sa.Column('implementation_time_days', sa.Integer(), nullable=True),
    sa.Column('priority_score', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('new', 'accepted', 'rejected', 'in_progress', 'done', name='hypothesis_status'), server_default='new', nullable=False),
    sa.Column('risks', sa.JSON(), nullable=True),
    sa.Column('data_sources', sa.JSON(), nullable=True),
    sa.Column('similar_cases', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['downtime_id'], ['downtimes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hypotheses')
    op.drop_table('inspections')
    op.drop_table('downtimes')
    op.drop_table('equipment')
    op.drop_table('equipment_types')
    # ### end Alembic commands ###
