"""empty message

Revision ID: 1517a2c5b15e
Revises: d45748553dfa
Create Date: 2026-05-03 13:54:25.024402

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "1517a2c5b15e"
down_revision: Union[str, None] = "d45748553dfa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "equipment_types",
        sa.Column(
            "is_active", sa.Boolean(), server_default="true", nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("equipment_types", "is_active")
    # ### end Alembic commands ###
